### ISSUE TITLE
CypressError: Expected to find content: 'Jenkins, Kuhn and Reilly' within the element: <tr.apartmentDetails> and with the selector: 'tr' but never did

### ISSUE THREAD

**Issue by ghost** [armadillo-apps/arms2#9]
**Failing test name:** 
Apartments, Occupant, and ApartmentAssign Create, edit, and view Apartment should create a new apartment and show apartment profile:

**Error message**

``Apartments, Occupant, and ApartmentAssign Create, edit, and view Apartment should create a new apartment and show apartment profile:
     CypressError: Timed out retrying: Expected to find content: 'Jenkins, Kuhn and Reilly' within the element: <tr.apartmentDetails> and with the selector: 'tr' but never did.
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:84963:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:84916:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:84947:17)
      at retry (http://localhost:3000/__cypress/runner/cypress_runner.js:77960:16)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:69765:18
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:134216:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:132234:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:132291:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:132336:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:132411:18)
      at Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:129140:16)
      at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:129150:10)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:129024:14)
      at <anonymous>
``

**Comment by ashleytanliling** [comment]
refer to #21
